# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-12 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wej', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurantImg',
            field=models.ImageField(upload_to='img/store/', verbose_name='store_'),
        ),
    ]
