# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-12 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wej', '0003_auto_20170612_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='restaurantMenuImg',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='callNumber',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.RemoveField(
            model_name='restaurantmenu',
            name='menuId',
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='menuId',
            field=models.ManyToManyField(to='wej.Menu'),
        ),
        migrations.RemoveField(
            model_name='restaurantmenu',
            name='restaurantId',
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='restaurantId',
            field=models.ManyToManyField(to='wej.Restaurant'),
        ),
    ]
