# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-12 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wej', '0004_auto_20170612_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='id',
            new_name='menuId',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='menuName',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='id',
            new_name='restaurantId',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='restaurantName',
        ),
        migrations.RemoveField(
            model_name='restaurantmenu',
            name='menuId',
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='menuId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='menu_rel', to='wej.Menu'),
        ),
        migrations.RemoveField(
            model_name='restaurantmenu',
            name='restaurantId',
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='restaurantId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_rel', to='wej.Restaurant'),
        ),
    ]
