# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-12 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wej', '0005_auto_20170612_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantmenu',
            old_name='menuId',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='restaurantmenu',
            old_name='restaurantId',
            new_name='restaurant',
        ),
    ]
