# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-12 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wej', '0006_auto_20170612_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantmenu',
            old_name='menu',
            new_name='menuId',
        ),
        migrations.RenameField(
            model_name='restaurantmenu',
            old_name='restaurant',
            new_name='restaurantId',
        ),
    ]
