# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wej', '0007_auto_20170612_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='count',
            new_name='searchCount',
        ),
    ]
