# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wej', '0008_auto_20170614_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('searchKeyword', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('searchCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
