# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wej', '0010_rate_restaurantmenuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='restaurantMenuId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='restaurantMenu_rel', to='wej.RestaurantMenu'),
        ),
    ]
